<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Tensor" data-toc-modified-id="Tensor-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Tensor</a></span></li><li><span><a href="#Autograd：自动微分" data-toc-modified-id="Autograd：自动微分-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Autograd：自动微分</a></span></li><li><span><a href="#神经网络" data-toc-modified-id="神经网络-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>神经网络</a></span><ul class="toc-item"><li><span><a href="#LeNet" data-toc-modified-id="LeNet-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>LeNet</a></span></li></ul></li></ul></div>

## Tensor

In [1]:
# py2中
#from __future__ import print_function
import torch as t

In [2]:
x = t.Tensor(5, 3)
x

tensor([[7.7442e+32, 6.9224e-43, 7.9751e+32],
        [6.9224e-43, 1.0148e+36, 6.9224e-43],
        [6.3687e+15, 0.0000e+00, 6.3687e+15],
        [0.0000e+00, 7.7442e+32, 6.9224e-43],
        [9.5692e+32, 6.9224e-43,        nan]])

In [3]:
x = t.rand(5, 3)
x

tensor([[0.4930, 0.7833, 0.9081],
        [0.1176, 0.8073, 0.1324],
        [0.1488, 0.1687, 0.5123],
        [0.1225, 0.0971, 0.5912],
        [0.7843, 0.3128, 0.3608]])

In [4]:
x.size()

torch.Size([5, 3])

In [5]:
x.size()[1]

3

In [6]:
x.size(1)

3

In [8]:
y = t.rand(5, 3)
x + y

tensor([[1.2927, 1.5768, 1.4509],
        [1.0517, 1.3996, 0.2756],
        [0.4492, 0.2679, 0.7251],
        [0.1952, 0.8912, 1.4520],
        [1.4583, 0.6500, 0.5162]])

In [9]:
t.add(x, y)

tensor([[1.2927, 1.5768, 1.4509],
        [1.0517, 1.3996, 0.2756],
        [0.4492, 0.2679, 0.7251],
        [0.1952, 0.8912, 1.4520],
        [1.4583, 0.6500, 0.5162]])

In [10]:
result = t.Tensor(5, 3)
t.add(x, y, out=result)
result

tensor([[1.2927, 1.5768, 1.4509],
        [1.0517, 1.3996, 0.2756],
        [0.4492, 0.2679, 0.7251],
        [0.1952, 0.8912, 1.4520],
        [1.4583, 0.6500, 0.5162]])

In [11]:
y

tensor([[0.7996, 0.7935, 0.5429],
        [0.9341, 0.5924, 0.1432],
        [0.3004, 0.0993, 0.2128],
        [0.0727, 0.7942, 0.8607],
        [0.6740, 0.3371, 0.1554]])

In [12]:
y.add(x)
y

tensor([[0.7996, 0.7935, 0.5429],
        [0.9341, 0.5924, 0.1432],
        [0.3004, 0.0993, 0.2128],
        [0.0727, 0.7942, 0.8607],
        [0.6740, 0.3371, 0.1554]])

In [13]:
y.add_(x)
y

tensor([[1.2927, 1.5768, 1.4509],
        [1.0517, 1.3996, 0.2756],
        [0.4492, 0.2679, 0.7251],
        [0.1952, 0.8912, 1.4520],
        [1.4583, 0.6500, 0.5162]])

In [14]:
x

tensor([[0.4930, 0.7833, 0.9081],
        [0.1176, 0.8073, 0.1324],
        [0.1488, 0.1687, 0.5123],
        [0.1225, 0.0971, 0.5912],
        [0.7843, 0.3128, 0.3608]])

In [15]:
x[:,1]

tensor([0.7833, 0.8073, 0.1687, 0.0971, 0.3128])

In [16]:
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [17]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
import numpy as np

In [19]:
a = np.ones(5)
b = t.from_numpy(a)
a

array([1., 1., 1., 1., 1.])

In [20]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [21]:
b.add_(1)
a

array([2., 2., 2., 2., 2.])

In [22]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

Tensor可以通过.cuda方法转换为GPU的Tensor，从而享受GPU带来的加速运算
```python
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y
```

## Autograd：自动微分
深度学习的算法本质上是通过反向传播求导数，PyTorch的Autograd模块实现了此功能。在Tensor上的所有操作，Autograd都能为他们自动提供微分，避免手动计算导数的麻烦。  

Autograd.Variable

In [23]:
from torch.autograd import Variable

In [25]:
x = Variable(t.ones(2, 2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [27]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [28]:
y.grad_fn

In [29]:
y.backward()

In [31]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [32]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [33]:
y.backward()
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [34]:
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [35]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [36]:
x = Variable(t.ones(4,5))
y = t.cos(x)
x_tensor_cos = t.cos(x.data)
y

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])

In [37]:
x_tensor_cos

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])

## 神经网络
torch.nn是专门为神经网络设计的模块化接口。  
nn构建于Autograd之上，可用来定义和运行神经网络。  


### LeNet

LeNet5诞生于1994年，由Yann LeCun提出，充分考虑图像的相关性。当时结构的特点如下：
1. 每个卷积层包含三个部分：卷积（Conv）、池化（ave-pooling）、非线性激活函数（sigmoid）
2. MLP作为最终的分类器
3. 层与层之间稀疏连接减少计算复杂度


- Input Layer：1*32*32图像  
- Conv1 Layer：包含6个卷积核，kernal size：5*5，parameters:（5*5+1）*6=156个
- Subsampling Layer：average pooling，size：2*2,Activation Function：sigmoid
- Conv3 Layer：包含16个卷积核，kernal size：5*5  ->16个Feature Map
- Subsampling Layer：average pooling，size：2*2
- Conv5 Layer：包含120个卷积核，kernal size：5*5
- Fully Connected Layer：Activation Function：sigmoid
- Output Layer：Gaussian connection

